title: Topher Collins # your name (or website title) here
logo: "/images/topherprofile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist and Machine Learning Practitioner
  <br><br>
  Python Developer (experiened with Flask frameworks)
  <br><br>
  <a href="https://www.linkedin.com/in/christopher-collins-47419555/">View My LinkedIn</a> 
  <br><br>
  <a href="https://medium.com/@tophercollins/">View My Articles on Medium</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
